### ISSUE TITLE
Ifcfg constructor fails when interface has empty angular brackers.

### ISSUE THREAD

**Issue by Rahul-RB** [sanketsudake/ifconfig-parser#14]
I have the following interface in my `ifconfig`:
`enc0: flags=0<> metric 0 mtu 1536`

The constructor call fails:
`ifdata = Ifcfg(commands.getoutput('ifconfig -a'))`
as:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.freebsd-8.4-RELEASE-amd64/egg/ifparser/ifconfig.py", line 106, in __init__
  File "build/bdist.freebsd-8.4-RELEASE-amd64/egg/ifparser/ifconfig.py", line 116, in _process
ifparser.ifconfig.ParseError: 'enc0: flags=0<> metric 0 mtu 1536'
```

**Comment by sanketsudake** [comment]
@Rahul-RB  Would be possible for you to capture ifconfig output in txt file attach here with gist or pastebin ?

**Comment by Rahul-RB** [comment]
Sure. 
Here's a [gist](https://gist.github.com/Rahul-RB/92704e463a7925fb3656694d35745ed9). Also attached is a text file having the same output.

[op.txt](https://github.com/ssudake21/ifconfig-parser/files/2820919/op.txt)
